# Catppuccin Mocha Color Palette

$base           = rgb(1e1e2e)
$surface0       = rgb(313244)
$overlay0       = rgb(6c7086)
$text           = rgb(cdd6f4)
$lavender       = rgb(b4befe)
$mauve          = rgb(cba6f7)
$red            = rgb(f38ba8)
$peach          = rgb(fab387)
$yellow         = rgb(f9e2af)
$green          = rgb(a6e3a1)
$teal           = rgb(94e2d5)
$blue           = rgb(89b4fa)